// Playlists actions
export const LOAD_PLAYLISTS_COMPLETE = 'LOAD_PLAYLISTS_COMPLETE';
export const LOAD_PLAYLIST_REQUEST = 'LOAD_PLAYLIST_REQUEST';
export const LOAD_PLAYLIST_COMPLETE = 'LOAD_PLAYLIST_COMPLETE';
